In [8]:
import pandas as pd
import os
import sys
sys.path.append(os.path.abspath("D:\kidlor\data_engineer\project\de_project").replace("\\", "/"))
from src.extract import fetch_users, get_data_csv

<>:4: SyntaxWarning: invalid escape sequence '\k'
<>:4: SyntaxWarning: invalid escape sequence '\k'
C:\Users\hieuh\AppData\Local\Temp\ipykernel_4660\4059003303.py:4: SyntaxWarning: invalid escape sequence '\k'
  sys.path.append(os.path.abspath("D:\kidlor\data_engineer\project\de_project").replace("\\", "/"))

In [10]:
df_api = fetch_users()
df_csv = pd.read_csv('../../data/orders.csv')

Status code: 200

In [3]:
df_api

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [11]:
df_csv

   order_id  user_id       product  quantity  price  order_date
0         1        1        Laptop         1   1200  2026-04-01
1         2        2         Mouse         2     25  2026-04-01
2         3        1      Keyboard         1     80  2026-04-02
3         4        3       Monitor         2    300  2026-04-02
4         5        4     USB Cable         5     10  2026-04-03
5         6       99     Headphone         1    150  2026-04-03
6         7        2  Laptop Stand         1     45  2026-04-04
7         8        3     Mouse Pad         3     12  2026-04-04

In [4]:
df_api.columns.tolist()

['id', 'name', 'username', 'email', 'address', 'phone', 'website', 'company']

In [5]:
df_api = df_api.rename(columns = {"id": "user_id"})

In [6]:
df_api['user_id'] = 'uc' + df_api['user_id'].astype(str)

In [17]:
df_api['city'] = df_api.apply(lambda row: row['address']['city'], axis=1)
df_api['company_name'] = df_api.apply(lambda row: row['company']['name'], axis=1)

In [19]:
df_api_main = df_api[['user_id', 'name', 'email','phone', 'city', 'company_name']]

In [ ]:
df_csv['user_id'] = 'uc' + df_csv['user_id'].astype(str)

In [20]:
df_api_main

,user_id,name,email,phone,city,company_name
0,uc1,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona
1,uc2,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist
2,uc3,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson
3,uc4,Patricia Lebsack,Julianne.OConner@kory.org,493-170-9623 x156,South Elvis,Robel-Corkery
4,uc5,Chelsey Dietrich,Lucio_Hettinger@annie.ca,(254)954-1289,Roscoeview,Keebler LLC
5,uc6,Mrs. Dennis Schulist,Karley_Dach@jasper.info,1-477-935-8478 x6430,South Christy,Considine-Lockman
6,uc7,Kurtis Weissnat,Telly.Hoeger@billy.biz,210.067.6132,Howemouth,Johns Group
7,uc8,Nicholas Runolfsdottir V,Sherwood@rosamond.me,586.493.6943 x140,Aliyaview,Abernathy Group
8,uc9,Glenna Reichert,Chaim_McDermott@dana.io,(775)976-6794 x41206,Bartholomebury,Yost and Sons
9,uc10,Clementina DuBuque,Rey.Padberg@karina.biz,024-648-3804,Lebsackbury,Hoeger LLC